### ISSUE TITLE
Failing one-hop testing

### ISSUE THREAD

**Issue by cbizon** [NCATS-Tangerine/icees-api#126] opened 2021-06-12 18:27 UTC
This TRAPI query:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "a": {
                    "categories": [
                        "biolink:ActivityAndBehavior"
                    ],
                    "ids": [
                        "UMLSCUI:C0562508"
                    ]
                },
                "b": {
                    "categories": [
                        "biolink:ActivityAndBehavior"
                    ]
                }
            },
            "edges": {
                "ab": {
                    "subject": "a",
                    "object": "b",
                    "predicates": [
                        "biolink:correlated_with"
                    ]
                }
            }
        },
        "knowledge_graph": {
            "nodes": {},
            "edges": {}
        },
        "results": []
    }
}
```

Is returning no results.

This is the first triple in our onehop test cases:
```
{
            "subject_category": "biolink:ActivityAndBehavior",
            "object_category": "biolink:ActivityAndBehavior",
            "predicate": "biolink:correlated_with",
            "subject": "UMLSCUI:C0562508",
            "object": "UMLSCUI:C2348993"
        },
```

Note that the prefixes were originally "umlscui" but I capitalized them to bring them into alignment with the /meta_knowledge_graph.

**Comment by karafecho** [comment] 2021-06-14 18:39
@xu-hao : Wee [this related issue](https://github.com/NCATS-Tangerine/icees-api/issues/100).

Looks like we will need to capitalize the prefixes when we move to Dhall for config files.

**Comment by cbizon** [comment] 2021-06-15 13:58
Note that the allowed prefixes are defined in the biolink model, either in https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml or in https://github.com/biolink/biolink-model/blob/master/context.jsonld

**Comment by karafecho** [comment] 2021-06-22 17:04
One-hop testing JSON file can be found [here](https://github.com/NCATSTranslator/testing/blob/bug_fix/onehop/templates/KP/Exposures_Provider/ICEES_API.json).

**Comment by karafecho** [comment] 2021-06-22 19:25
I think the issue here relates not to the template, but rather to the fact that the subject and object CURIES are mapping to the same node.

**Comment by xu-hao** [comment] 2021-06-22 20:24
This is caused by variables such as `TotalEDInpatientVisit` not having a finite value set, therefore cannot calculate p value. We need to define a binning strategy for these variables. @karafecho  is 0, 1, ..., 9, 10+ ok?

**Comment by karafecho** [comment] 2021-06-22 20:36
The proposed binning strategy is perfectly reasonable, but this won't address the fact that the subject and object CURIES are mapping to the same node. I guess technically it's perfectly fine to calculate and return a chi square test of this sort, but scientifically it seems a bit weird. That said, if this resolves the issue, then I really don't have a strong opinion.

**Comment by karafecho** [comment] 2021-06-22 21:27
Also, note that we will have the same issue with RoadwayAADT and all of the DILI lab values. The RoadwayAADT variable was intended to be used to improve our models for estimating roadway/highway exposures, but we haven't used it (yet). I posted a ticket a while back to remove it from the API. We intentionally did not bin the DILI lab values, partially in response to requests we received from Translator team members who desired more granular metrics. We don't have reference ranges to aid with interpretation of those values, but we do have translations to "X times upper level of normal", so we can probably just remove the lab values. Off the top of my head, I think those are the only feature variables that will create issues with the TRAPI tests, but I can check to see if there are others.

**Comment by xu-hao** [comment] 2021-06-22 23:09
Resolved by binning the data and updating the mapping. The query returns one result now such that `UMLSCUI:C2348993` is in the `biolink:synomyn` attribute of the returned node.

**Comment by mmersmann** [comment] 2021-06-28 17:11
@patrickkwang to confirm complete

**Comment by patrickkwang** [comment] 2021-07-19 17:54
This works now.

**Closed by patrickkwang** 2021-07-19 17:54 UTC
