### ISSUE TITLE
icees shows up as n/a on ars

### ISSUE THREAD

**Issue by xu-hao** [NCATS-Tangerine/icees-api#161] opened 2021-08-11 17:18 UTC
should be 0

examples pk: 379c6b8a-a728-42c8-b537-2a450f395aae

it appears that the validation passed we need to figure out why it's not showing 0 which is expected on the arax ars result

**Comment by patrickkwang** [comment] 2021-10-05 18:51
Duplicate of #140

**Closed by patrickkwang** 2021-10-05 18:51 UTC
